#Sample docker compose files which brings up one mongo instance
#docker-compose -f docker_compose.yaml up
#docker-compose -f docker_compose.yaml down
#docker-compose -f docker_compose.yaml start
#docker-compose -f docker_compose.yaml stop

---
version : '3.1'
services:
  mongo_db:
   image: mongo:latest
   ports:
    - '27018:27017'
   environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
...
  
  